language: go

go:
    - "1.7"

env:
    global:
        - SSH_KEY="id_rsa"
        - GIT_NAME="Kidon Chu"
        - GIT_EMAIL="kidonchu@gmail.com"
        - SOURCE_DIR="public"
        - DEPLOY_BRANCH="master"

before_install:
    - openssl aes-256-cbc -K $encrypted_1e2d135be8b5_key -iv $encrypted_1e2d135be8b5_iv -in travis_rsa.enc -out travis_rsa -d

before_script:
    - go get -u -v github.com/spf13/hugo

script:
    - git clone https://github.com/jpescador/hugo-future-imperfect ./themes/hugo-future-imperfect
    - hugo

deploy:
    provider: script
    script: ./scripts/deploy.sh
    on:
        branch: master
