language: go

go:
    - "1.7"

before_install:
    - openssl aes-256-cbc -K $encrypted_1e2d135be8b5_key -iv $encrypted_1e2d135be8b5_iv -in deploy_key.enc -out deploy_key -d

script:
    - go get -u -v github.com/spf13/hugo
    - git clone https://github.com/jpescador/hugo-future-imperfect ./themes/hugo-future-imperfect
    - bash scripts/deploy.sh
